name: Zastepstwa Bot

on:
  workflow_dispatch: # Pozwala na ręczne odpalenie z telefonu/przeglądarki

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dostęp do zapisywania zaktualizowanej bazy danych w repozytorium

    steps:
      - name: Pobierz najnowszy kod i stan bazy
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalacja wymaganych pakietów
        run: |
          pip install httpx "httpx[http2]" aiosqlite

      - name: Uruchomienie skanera
        env:
          DISCORD_WEBHOOK_URL_2: ${{ secrets.DISCORD_WEBHOOK_URL_2 }}
        run: |
          python zastepstwa_bot.py
